#!/bin/bash

############################################################################
#
# Copyright (c) 2013 - Kyle Frost (frostincredible@gmail.com)
#        Mod by ( ptichalouf@gmail.com)
# This setup script is 100% free.  This script file is intended for personal
# and/or educational use only.         It may not be duplicated for monetary
# benefit  or  any other purpose  without  the permission  of the developer.
#
############################################################################

export PATH=/opt/local/bin:$PATH

POSIXLY_CORRECT=1 sudo port install gmake libsdl git-core gnupg

